include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info

linter:
  rules:
    - cancel_subscriptions